services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-allaria-hub-front}
    container_name: allaria-hub-front
    restart: always
    ports:
      - "3097:3097"
    networks:
      - red-docker

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: ${IMAGE_NAME_BACK:-allaria-hub-back}
    container_name: allaria-hub-back
    restart: always
    ports:
      - "3098:3098"
    env_file:
      - ./back/.env
    networks:
      - red-docker

volumes:
  sfs_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=172.30.20.83,rw,nolock,hard,nointr,nfsvers=3,proto=tcp"
      device: ":/SFS/${REPO_NAME}/"

networks:
  red-docker:
    external: true
