services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-${REPO_NAME:-allaria-hub}}
    container_name: ${REPO_NAME:-allaria-hub}
    restart: always

    ports:
      - "3097:3097"

    environment:
      - REPO_NAME=${REPO_NAME}
      - APP_PORT=3097

    env_file:
      - .env

    volumes:
      - sfs_data:/data

    networks:
      - red-docker

volumes:
  sfs_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=172.30.20.83,rw,nolock,hard,nointr,nfsvers=3,proto=tcp"
      device: ":/SFS/${REPO_NAME}/"

networks:
  red-docker:
    external: true
