apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: allaria-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      imagePullSecrets:
        - name: swr-pull-secret
      containers:
        - name: front
          image: swr.la-south-2.myhuaweicloud.com/allaria-sandbox/allaria-hub-front:latest
          ports:
            - containerPort: 3097
          readinessProbe:
            httpGet:
              path: /
              port: 3097
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: allaria-hub
  annotations:
    kubernetes.io/elb.class: "union"
    kubernetes.io/elb.autocreate: '{"type":"public","bandwidth_name":"allaria-hub-lb","bandwidth_chargemode":"traffic","bandwidth_size":5,"bandwidth_sharetype":"PER","eip_type":"5_bgp"}'
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
    - port: 80
      targetPort: 3097
