apiVersion: v1
kind: Namespace
metadata:
  name: user-projects
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: projects-router-manager
  namespace: user-projects
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hub-back-router-manager
  namespace: user-projects
subjects:
  - kind: ServiceAccount
    name: hub-back
    namespace: allaria-hub
roleRef:
  kind: Role
  name: projects-router-manager
  apiGroup: rbac.authorization.k8s.io
